
# html lang
language: zh-cn

# main menu navigation
menu:
  Home: /
  About: /about

# stylesheets loaded in the <head>
stylesheets:
- /css/shiro.css
- /css/layout.css
- /css/post.css
- /css/content.css
- /css/highlight.css
- /lib/soraka/soraka.css
- /lib/typo.css/typo.css

# SEO
google_site_verification:
  enable: true
  verification_code:

baidu_site_verification:
  enable: true
  verification_code:



# scripts loaded in the end of the body
scripts:
- /js/shiro.js
