
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/shiro.css
- /css/layout.css
- /css/post.css
- /css/content.css
- /lib/soraka/soraka.css
- /lib/typo.css/typo.css

# scripts loaded in the end of the body
scripts:
- /js/shiro.js

